// Code generated by gen/main.go; DO NOT EDIT.

package anyto

import (
	"time"

	"github.com/spf13/cast"
)

// Bool converts the value to *bool, returning nil on error.
func (a AnyPointer) Bool() *bool {
	v, err := cast.ToBoolE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// String converts the value to *string, returning nil on error.
func (a AnyPointer) String() *string {
	v, err := cast.ToStringE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Int converts the value to *int, returning nil on error.
func (a AnyPointer) Int() *int {
	v, err := cast.ToIntE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Int8 converts the value to *int8, returning nil on error.
func (a AnyPointer) Int8() *int8 {
	v, err := cast.ToInt8E(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Int16 converts the value to *int16, returning nil on error.
func (a AnyPointer) Int16() *int16 {
	v, err := cast.ToInt16E(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Int32 converts the value to *int32, returning nil on error.
func (a AnyPointer) Int32() *int32 {
	v, err := cast.ToInt32E(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Int64 converts the value to *int64, returning nil on error.
func (a AnyPointer) Int64() *int64 {
	v, err := cast.ToInt64E(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Uint converts the value to *uint, returning nil on error.
func (a AnyPointer) Uint() *uint {
	v, err := cast.ToUintE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Uint8 converts the value to *uint8, returning nil on error.
func (a AnyPointer) Uint8() *uint8 {
	v, err := cast.ToUint8E(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Uint16 converts the value to *uint16, returning nil on error.
func (a AnyPointer) Uint16() *uint16 {
	v, err := cast.ToUint16E(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Uint32 converts the value to *uint32, returning nil on error.
func (a AnyPointer) Uint32() *uint32 {
	v, err := cast.ToUint32E(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Uint64 converts the value to *uint64, returning nil on error.
func (a AnyPointer) Uint64() *uint64 {
	v, err := cast.ToUint64E(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Float32 converts the value to *float32, returning nil on error.
func (a AnyPointer) Float32() *float32 {
	v, err := cast.ToFloat32E(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Float64 converts the value to *float64, returning nil on error.
func (a AnyPointer) Float64() *float64 {
	v, err := cast.ToFloat64E(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Time converts the value to *time.Time, returning nil on error.
func (a AnyPointer) Time() *time.Time {
	v, err := cast.ToTimeE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Duration converts the value to *time.Duration, returning nil on error.
func (a AnyPointer) Duration() *time.Duration {
	v, err := cast.ToDurationE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Slice converts the value to *[]any, returning nil on error.
func (a AnyPointer) Slice() *[]any {
	v, err := cast.ToSliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// BoolSlice converts the value to *[]bool, returning nil on error.
func (a AnyPointer) BoolSlice() *[]bool {
	v, err := cast.ToBoolSliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// StringSlice converts the value to *[]string, returning nil on error.
func (a AnyPointer) StringSlice() *[]string {
	v, err := cast.ToStringSliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// IntSlice converts the value to *[]int, returning nil on error.
func (a AnyPointer) IntSlice() *[]int {
	v, err := cast.ToIntSliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Int8Slice converts the value to *[]int8, returning nil on error.
func (a AnyPointer) Int8Slice() *[]int8 {
	v, err := cast.ToInt8SliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Int16Slice converts the value to *[]int16, returning nil on error.
func (a AnyPointer) Int16Slice() *[]int16 {
	v, err := cast.ToInt16SliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Int32Slice converts the value to *[]int32, returning nil on error.
func (a AnyPointer) Int32Slice() *[]int32 {
	v, err := cast.ToInt32SliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Int64Slice converts the value to *[]int64, returning nil on error.
func (a AnyPointer) Int64Slice() *[]int64 {
	v, err := cast.ToInt64SliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// UintSlice converts the value to *[]uint, returning nil on error.
func (a AnyPointer) UintSlice() *[]uint {
	v, err := cast.ToUintSliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Uint8Slice converts the value to *[]uint8, returning nil on error.
func (a AnyPointer) Uint8Slice() *[]uint8 {
	v, err := cast.ToUint8SliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Uint16Slice converts the value to *[]uint16, returning nil on error.
func (a AnyPointer) Uint16Slice() *[]uint16 {
	v, err := cast.ToUint16SliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Uint32Slice converts the value to *[]uint32, returning nil on error.
func (a AnyPointer) Uint32Slice() *[]uint32 {
	v, err := cast.ToUint32SliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Uint64Slice converts the value to *[]uint64, returning nil on error.
func (a AnyPointer) Uint64Slice() *[]uint64 {
	v, err := cast.ToUint64SliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Float32Slice converts the value to *[]float32, returning nil on error.
func (a AnyPointer) Float32Slice() *[]float32 {
	v, err := cast.ToFloat32SliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// Float64Slice converts the value to *[]float64, returning nil on error.
func (a AnyPointer) Float64Slice() *[]float64 {
	v, err := cast.ToFloat64SliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// DurationSlice converts the value to *[]time.Duration, returning nil on error.
func (a AnyPointer) DurationSlice() *[]time.Duration {
	v, err := cast.ToDurationSliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// StringMap converts the value to *map[string]any, returning nil on error.
func (a AnyPointer) StringMap() *map[string]any {
	v, err := cast.ToStringMapE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// StringMapString converts the value to *map[string]string, returning nil on error.
func (a AnyPointer) StringMapString() *map[string]string {
	v, err := cast.ToStringMapStringE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// StringMapStringSlice converts the value to *map[string][]string, returning nil on error.
func (a AnyPointer) StringMapStringSlice() *map[string][]string {
	v, err := cast.ToStringMapStringSliceE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// StringMapBool converts the value to *map[string]bool, returning nil on error.
func (a AnyPointer) StringMapBool() *map[string]bool {
	v, err := cast.ToStringMapBoolE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// StringMapInt converts the value to *map[string]int, returning nil on error.
func (a AnyPointer) StringMapInt() *map[string]int {
	v, err := cast.ToStringMapIntE(a.v)
	if err != nil {
		return nil
	}
	return &v
}

// StringMapInt64 converts the value to *map[string]int64, returning nil on error.
func (a AnyPointer) StringMapInt64() *map[string]int64 {
	v, err := cast.ToStringMapInt64E(a.v)
	if err != nil {
		return nil
	}
	return &v
}
