// Code generated by gen/main.go; DO NOT EDIT.

package anyto

import (
	"time"

	"github.com/spf13/cast"
)

// Bool converts the value to *bool, returning (nil, error) on failure.
func (a *anyPointerE) Bool() (*bool, error) {
	v, err := cast.ToBoolE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// String converts the value to *string, returning (nil, error) on failure.
func (a *anyPointerE) String() (*string, error) {
	v, err := cast.ToStringE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Int converts the value to *int, returning (nil, error) on failure.
func (a *anyPointerE) Int() (*int, error) {
	v, err := cast.ToIntE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Int8 converts the value to *int8, returning (nil, error) on failure.
func (a *anyPointerE) Int8() (*int8, error) {
	v, err := cast.ToInt8E(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Int16 converts the value to *int16, returning (nil, error) on failure.
func (a *anyPointerE) Int16() (*int16, error) {
	v, err := cast.ToInt16E(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Int32 converts the value to *int32, returning (nil, error) on failure.
func (a *anyPointerE) Int32() (*int32, error) {
	v, err := cast.ToInt32E(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Int64 converts the value to *int64, returning (nil, error) on failure.
func (a *anyPointerE) Int64() (*int64, error) {
	v, err := cast.ToInt64E(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Uint converts the value to *uint, returning (nil, error) on failure.
func (a *anyPointerE) Uint() (*uint, error) {
	v, err := cast.ToUintE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Uint8 converts the value to *uint8, returning (nil, error) on failure.
func (a *anyPointerE) Uint8() (*uint8, error) {
	v, err := cast.ToUint8E(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Uint16 converts the value to *uint16, returning (nil, error) on failure.
func (a *anyPointerE) Uint16() (*uint16, error) {
	v, err := cast.ToUint16E(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Uint32 converts the value to *uint32, returning (nil, error) on failure.
func (a *anyPointerE) Uint32() (*uint32, error) {
	v, err := cast.ToUint32E(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Uint64 converts the value to *uint64, returning (nil, error) on failure.
func (a *anyPointerE) Uint64() (*uint64, error) {
	v, err := cast.ToUint64E(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Float32 converts the value to *float32, returning (nil, error) on failure.
func (a *anyPointerE) Float32() (*float32, error) {
	v, err := cast.ToFloat32E(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Float64 converts the value to *float64, returning (nil, error) on failure.
func (a *anyPointerE) Float64() (*float64, error) {
	v, err := cast.ToFloat64E(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Time converts the value to *time.Time, returning (nil, error) on failure.
func (a *anyPointerE) Time() (*time.Time, error) {
	v, err := cast.ToTimeE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Duration converts the value to *time.Duration, returning (nil, error) on failure.
func (a *anyPointerE) Duration() (*time.Duration, error) {
	v, err := cast.ToDurationE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Slice converts the value to *[]any, returning (nil, error) on failure.
func (a *anyPointerE) Slice() (*[]any, error) {
	v, err := cast.ToSliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// BoolSlice converts the value to *[]bool, returning (nil, error) on failure.
func (a *anyPointerE) BoolSlice() (*[]bool, error) {
	v, err := cast.ToBoolSliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// StringSlice converts the value to *[]string, returning (nil, error) on failure.
func (a *anyPointerE) StringSlice() (*[]string, error) {
	v, err := cast.ToStringSliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// IntSlice converts the value to *[]int, returning (nil, error) on failure.
func (a *anyPointerE) IntSlice() (*[]int, error) {
	v, err := cast.ToIntSliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Int8Slice converts the value to *[]int8, returning (nil, error) on failure.
func (a *anyPointerE) Int8Slice() (*[]int8, error) {
	v, err := cast.ToInt8SliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Int16Slice converts the value to *[]int16, returning (nil, error) on failure.
func (a *anyPointerE) Int16Slice() (*[]int16, error) {
	v, err := cast.ToInt16SliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Int32Slice converts the value to *[]int32, returning (nil, error) on failure.
func (a *anyPointerE) Int32Slice() (*[]int32, error) {
	v, err := cast.ToInt32SliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Int64Slice converts the value to *[]int64, returning (nil, error) on failure.
func (a *anyPointerE) Int64Slice() (*[]int64, error) {
	v, err := cast.ToInt64SliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// UintSlice converts the value to *[]uint, returning (nil, error) on failure.
func (a *anyPointerE) UintSlice() (*[]uint, error) {
	v, err := cast.ToUintSliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Uint8Slice converts the value to *[]uint8, returning (nil, error) on failure.
func (a *anyPointerE) Uint8Slice() (*[]uint8, error) {
	v, err := cast.ToUint8SliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Uint16Slice converts the value to *[]uint16, returning (nil, error) on failure.
func (a *anyPointerE) Uint16Slice() (*[]uint16, error) {
	v, err := cast.ToUint16SliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Uint32Slice converts the value to *[]uint32, returning (nil, error) on failure.
func (a *anyPointerE) Uint32Slice() (*[]uint32, error) {
	v, err := cast.ToUint32SliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Uint64Slice converts the value to *[]uint64, returning (nil, error) on failure.
func (a *anyPointerE) Uint64Slice() (*[]uint64, error) {
	v, err := cast.ToUint64SliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Float32Slice converts the value to *[]float32, returning (nil, error) on failure.
func (a *anyPointerE) Float32Slice() (*[]float32, error) {
	v, err := cast.ToFloat32SliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// Float64Slice converts the value to *[]float64, returning (nil, error) on failure.
func (a *anyPointerE) Float64Slice() (*[]float64, error) {
	v, err := cast.ToFloat64SliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// DurationSlice converts the value to *[]time.Duration, returning (nil, error) on failure.
func (a *anyPointerE) DurationSlice() (*[]time.Duration, error) {
	v, err := cast.ToDurationSliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// StringMap converts the value to *map[string]any, returning (nil, error) on failure.
func (a *anyPointerE) StringMap() (*map[string]any, error) {
	v, err := cast.ToStringMapE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// StringMapString converts the value to *map[string]string, returning (nil, error) on failure.
func (a *anyPointerE) StringMapString() (*map[string]string, error) {
	v, err := cast.ToStringMapStringE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// StringMapStringSlice converts the value to *map[string][]string, returning (nil, error) on failure.
func (a *anyPointerE) StringMapStringSlice() (*map[string][]string, error) {
	v, err := cast.ToStringMapStringSliceE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// StringMapBool converts the value to *map[string]bool, returning (nil, error) on failure.
func (a *anyPointerE) StringMapBool() (*map[string]bool, error) {
	v, err := cast.ToStringMapBoolE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// StringMapInt converts the value to *map[string]int, returning (nil, error) on failure.
func (a *anyPointerE) StringMapInt() (*map[string]int, error) {
	v, err := cast.ToStringMapIntE(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// StringMapInt64 converts the value to *map[string]int64, returning (nil, error) on failure.
func (a *anyPointerE) StringMapInt64() (*map[string]int64, error) {
	v, err := cast.ToStringMapInt64E(a.v)
	if err != nil {
		return nil, err
	}
	return &v, nil
}
