// Code generated by gen/main.go; DO NOT EDIT.

package anyto

import (
	"time"

	"github.com/spf13/cast"
)

// Bool converts the value to bool, returning the zero value on error.
func (a AnyValue) Bool() bool {
	v, _ := cast.ToBoolE(a.v)
	return v
}

// String converts the value to string, returning the zero value on error.
func (a AnyValue) String() string {
	v, _ := cast.ToStringE(a.v)
	return v
}

// Int converts the value to int, returning the zero value on error.
func (a AnyValue) Int() int {
	v, _ := cast.ToIntE(a.v)
	return v
}

// Int8 converts the value to int8, returning the zero value on error.
func (a AnyValue) Int8() int8 {
	v, _ := cast.ToInt8E(a.v)
	return v
}

// Int16 converts the value to int16, returning the zero value on error.
func (a AnyValue) Int16() int16 {
	v, _ := cast.ToInt16E(a.v)
	return v
}

// Int32 converts the value to int32, returning the zero value on error.
func (a AnyValue) Int32() int32 {
	v, _ := cast.ToInt32E(a.v)
	return v
}

// Int64 converts the value to int64, returning the zero value on error.
func (a AnyValue) Int64() int64 {
	v, _ := cast.ToInt64E(a.v)
	return v
}

// Uint converts the value to uint, returning the zero value on error.
func (a AnyValue) Uint() uint {
	v, _ := cast.ToUintE(a.v)
	return v
}

// Uint8 converts the value to uint8, returning the zero value on error.
func (a AnyValue) Uint8() uint8 {
	v, _ := cast.ToUint8E(a.v)
	return v
}

// Uint16 converts the value to uint16, returning the zero value on error.
func (a AnyValue) Uint16() uint16 {
	v, _ := cast.ToUint16E(a.v)
	return v
}

// Uint32 converts the value to uint32, returning the zero value on error.
func (a AnyValue) Uint32() uint32 {
	v, _ := cast.ToUint32E(a.v)
	return v
}

// Uint64 converts the value to uint64, returning the zero value on error.
func (a AnyValue) Uint64() uint64 {
	v, _ := cast.ToUint64E(a.v)
	return v
}

// Float32 converts the value to float32, returning the zero value on error.
func (a AnyValue) Float32() float32 {
	v, _ := cast.ToFloat32E(a.v)
	return v
}

// Float64 converts the value to float64, returning the zero value on error.
func (a AnyValue) Float64() float64 {
	v, _ := cast.ToFloat64E(a.v)
	return v
}

// Time converts the value to time.Time, returning the zero value on error.
func (a AnyValue) Time() time.Time {
	v, _ := cast.ToTimeE(a.v)
	return v
}

// Duration converts the value to time.Duration, returning the zero value on error.
func (a AnyValue) Duration() time.Duration {
	v, _ := cast.ToDurationE(a.v)
	return v
}

// Slice converts the value to []any, returning the zero value on error.
func (a AnyValue) Slice() []any {
	v, _ := cast.ToSliceE(a.v)
	return v
}

// BoolSlice converts the value to []bool, returning the zero value on error.
func (a AnyValue) BoolSlice() []bool {
	v, _ := cast.ToBoolSliceE(a.v)
	return v
}

// StringSlice converts the value to []string, returning the zero value on error.
func (a AnyValue) StringSlice() []string {
	v, _ := cast.ToStringSliceE(a.v)
	return v
}

// IntSlice converts the value to []int, returning the zero value on error.
func (a AnyValue) IntSlice() []int {
	v, _ := cast.ToIntSliceE(a.v)
	return v
}

// Int8Slice converts the value to []int8, returning the zero value on error.
func (a AnyValue) Int8Slice() []int8 {
	v, _ := cast.ToInt8SliceE(a.v)
	return v
}

// Int16Slice converts the value to []int16, returning the zero value on error.
func (a AnyValue) Int16Slice() []int16 {
	v, _ := cast.ToInt16SliceE(a.v)
	return v
}

// Int32Slice converts the value to []int32, returning the zero value on error.
func (a AnyValue) Int32Slice() []int32 {
	v, _ := cast.ToInt32SliceE(a.v)
	return v
}

// Int64Slice converts the value to []int64, returning the zero value on error.
func (a AnyValue) Int64Slice() []int64 {
	v, _ := cast.ToInt64SliceE(a.v)
	return v
}

// UintSlice converts the value to []uint, returning the zero value on error.
func (a AnyValue) UintSlice() []uint {
	v, _ := cast.ToUintSliceE(a.v)
	return v
}

// Uint8Slice converts the value to []uint8, returning the zero value on error.
func (a AnyValue) Uint8Slice() []uint8 {
	v, _ := cast.ToUint8SliceE(a.v)
	return v
}

// Uint16Slice converts the value to []uint16, returning the zero value on error.
func (a AnyValue) Uint16Slice() []uint16 {
	v, _ := cast.ToUint16SliceE(a.v)
	return v
}

// Uint32Slice converts the value to []uint32, returning the zero value on error.
func (a AnyValue) Uint32Slice() []uint32 {
	v, _ := cast.ToUint32SliceE(a.v)
	return v
}

// Uint64Slice converts the value to []uint64, returning the zero value on error.
func (a AnyValue) Uint64Slice() []uint64 {
	v, _ := cast.ToUint64SliceE(a.v)
	return v
}

// Float32Slice converts the value to []float32, returning the zero value on error.
func (a AnyValue) Float32Slice() []float32 {
	v, _ := cast.ToFloat32SliceE(a.v)
	return v
}

// Float64Slice converts the value to []float64, returning the zero value on error.
func (a AnyValue) Float64Slice() []float64 {
	v, _ := cast.ToFloat64SliceE(a.v)
	return v
}

// DurationSlice converts the value to []time.Duration, returning the zero value on error.
func (a AnyValue) DurationSlice() []time.Duration {
	v, _ := cast.ToDurationSliceE(a.v)
	return v
}

// StringMap converts the value to map[string]any, returning the zero value on error.
func (a AnyValue) StringMap() map[string]any {
	v, _ := cast.ToStringMapE(a.v)
	return v
}

// StringMapString converts the value to map[string]string, returning the zero value on error.
func (a AnyValue) StringMapString() map[string]string {
	v, _ := cast.ToStringMapStringE(a.v)
	return v
}

// StringMapStringSlice converts the value to map[string][]string, returning the zero value on error.
func (a AnyValue) StringMapStringSlice() map[string][]string {
	v, _ := cast.ToStringMapStringSliceE(a.v)
	return v
}

// StringMapBool converts the value to map[string]bool, returning the zero value on error.
func (a AnyValue) StringMapBool() map[string]bool {
	v, _ := cast.ToStringMapBoolE(a.v)
	return v
}

// StringMapInt converts the value to map[string]int, returning the zero value on error.
func (a AnyValue) StringMapInt() map[string]int {
	v, _ := cast.ToStringMapIntE(a.v)
	return v
}

// StringMapInt64 converts the value to map[string]int64, returning the zero value on error.
func (a AnyValue) StringMapInt64() map[string]int64 {
	v, _ := cast.ToStringMapInt64E(a.v)
	return v
}
